name: ContosoUniversity

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'infra/**'
      - '**/ContosoUniversity - Infra.yml'
      - '**/README.md'
  pull_request:
    branches: 
      - main
    paths-ignore:
      - 'infra/**'
# We also want to be able to run this manually from Github
  workflow_dispatch:
  
env:
  CONFIGURATION: release
  AZ_APP_NAME: ${{secrets.AZURE_APP_NAME}}-app
  AZ_API_NAME: ${{ secrets.AZURE_APP_NAME }}-api

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    
    - name: Restore
      run: dotnet restore src/ContosoUniversity.sln
    
    - name: Build
      run: dotnet build src/ContosoUniversity.sln --configuration ${{ env.CONFIGURATION }} --no-restore
    
    - name: Test
      run: dotnet test src/ContosoUniversity.Test/ContosoUniversity.Test.csproj --verbosity normal --logger trx --results-directory TestResults
      
    - name: Publish APP
      run: dotnet publish --configuration ${{ env.CONFIGURATION }} --output PublishApp src/ContosoUniversity.WebApplication/ContosoUniversity.WebApplication.csproj

    - name: Publish API
      run: dotnet publish --configuration ${{ env.CONFIGURATION }} --output PublishApi src/ContosoUniversity.API/ContosoUniversity.API.csproj
    
    - name: Upload APP results
      uses: actions/upload-artifact@v2
      with:
        name: app
        path: PublishApp
    
    - name: Upload API results
      uses: actions/upload-artifact@v2
      with:
        name: api
        path: PublishApi
  
  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download APP Artifact
        uses: actions/download-artifact@v2
        with:
          name: app
          path: app-artifact
      
      - name: Download API Artifact
        uses: actions/download-artifact@v2
        with:
          name: api
          path: api-artifact
                 
      - name: ACR build
        id: build-push-acr
        uses: azure/acr-build@v1
        with:
          service_principal: ${{ secrets.service_principal }}
          service_principal_password: ${{ secrets.service_principal_password }}
          tenant: ${{ secrets.tenant }}
          registry: ${{ secrets.registry }}
          repository: ${{ secrets.repository }}
          image:  contosouniversity
          folder: src/ContosoUniversity.WebApplication/Dockerfile
          dockerfile: src/ContosoUniversity.WebApplication/Dockerfile
          branch: master
          tag: latest
      - name: Azure login
        id: login
        uses: azure/login@v1.4.3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Set AKS context
        id: set-context
        uses: azure/aks-set-context@v3
        with:
          resource-group: '${{ secrets.resource_group }}' 
          cluster-name: '${{ secrets.cluster_name }}'
      - name: Setup kubectl
        id: install-kubectl
        uses: azure/setup-kubectl@v3
